<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" 
    "http://www.w3.org/TR/REC-html40/loose.dtd"> 
<%@ LANGUAGE="JSCRIPT" %>
<html>
<head>
    <script language="JScript" type="text/jscript" runat="server">
        //
        // This runs in an <iframe> since AJAX uploading ain't practical
        // See my TiddlyWiki HandlingIFrames.html for how iframes embedded
        // within Tiddlers are made to work seampessly, including 
        // inheriting styles. It's magic!
        //
        // history
        //
        // 28-Sep-2011  rbd 3.3 Initial edit, from other iframe-based upload tiddlers
        // 30-Sep-2011  rbd 3.4 Add ACP user compression hack for AcquireScheduler
        // 21-Jan-14    rbd 7.1 GEM:965 No more DBRelay object. Uaing ACP API.
		// 05-Feb-2022  cle copied from Submit RTML
        //
    	function dispTime(t)
    	{
    	    if(t >= 3600)
    	    {
    	        t /= 3600;
    	        return t.toFixed(2) + "h";
    	    }
    	    else
    	    {
    	        t /= 60;
    	        return t.toFixed(1) + "min";
    	    }
        }

        //White space removal since JScript doesn't have a useful version.
        function trim(s) {
            return s.replace(/^[\s\xA0\r]+|[\s\xA0\r]+$/g, '');
        }

        //Maps possible similar filter names to the real filter name. Make sure the right side matches ACP & Maxim
        function filter_selection(f) {
            var filter_dict = {
                'LUM': 'Lum', 'L': 'Lum',
                'SII': 'SII', 'S2': 'SII',
                'HA': 'Ha', 'H': 'Ha',
                'OIII': 'OIII', 'O3': 'OIII',
                'B': 'B',
                'V': 'V', 'G': 'V',
                'R': 'R', 'SR': 'R',
                'I': 'I', 'SI': 'I',
            };
            f = f.toUpperCase();
            if (f in filter_dict) {
                return filter_dict[f];
            } else {
                throw "Unmapped filter: " + f;
            }
        }

        //Parses an ATMoB Submission Style CSV (Comma delimited, ASCII chacters only)
        //Argument is CSV text from submitted file
        //returns array of 2 elements
        //1st element is an array of tags from #TAG=VALUE entries in file
        //2nd element is an array of plans with keys taken from the first non-# row and values from each column of each row
        function parse_atmob_csv(csv_text) {
            var tags = {};
            var headers = [];
            var plans = [];
            var lines = [];
            //strip byte order mark generated by Microsoft programs
            if (csv_text.slice(0, 3) == "\xEF\xBB\xBF") {
                Response.Write("<p>Byte Order Mark detected. Nuking it</p>");
                csv_text = csv_text.slice(3);
            }
            var lines_all = csv_text.split("\n"); //Break file up by newline character. Should work for all CSV formats

            for (l = 0; l < lines_all.length; l++) {
                var line = lines_all[l];
                //Response.Write("<p>startswith</p>");
                if (line[0] == '#') {
                    line = line.slice(1); //Remove #
                    var t = line.split(','); // Tag, Value, *ignore*
                    if (t.length>1) {
                        for (i = 0; i < t.length; i++) {
                            t[i] = trim(t[i]); //Trim whitespace
                        }
                        //Response.Write("<p>" + t[0] + ' = ' + t[1] + "</p>")
                        tags[t[0]] = t[1]; //assign value to key
                    }
                } else {
                    lines.push(line); //non-# line. Add it to lines parsed later.
                }
            }
            //Response.Write("<p>"+tags['PROPOSAL']+"</p>");

            //Response.Write("<p>split1</p>");
            //headers is pulled from the first line in the CSV that is not a tagged line
            var headers = lines[0].split(",");
            //Response.Write("<p>split2</p>");
            //Remove the extra white space in headers
            for (h = 0; h < headers.length; h++) {
                headers[h] = trim(headers[h]);
                //Response.Write("<p>" + headers[h] + "</p>");
            }
            //Response.Write("<p>heads</p>");

            //Iterate through lines and generate plan objects with keys from header for column and value from column entry for row
            for (i = 1; i < lines.length; i++) {
                var plan = {};
                //Response.Write("<p>element_split</p>");
                var elements = lines[i].split(",");
                //Response.Write("<p>"+elements+"</p>")
                //Response.Write("<p>element_loop</p>");
                for (j = 0; j < elements.length; j++) {
                    //Response.Write("<p>"+elements[j]+"</p>")
                    plan[headers[j]] = trim(elements[j]); //Remove extra whitespace
                }
                //Response.Write("<p>push</p>");
                plans.push(plan);
            }
            //Response.Write("<p>Done</p>");
            return [tags, plans];
        }

        //Generate RTML for photometry targets
        function generate_photometry_rtml(tags, plans) {
            //Check if all required tags are present
            var tag_req = ["CONTACT", "CONTACT_EMAIL", "PROJECT"];
            for (i = 0; i < tag_req.length; i++) {
                if (!(tag_req[i] in tags)) {
                    //Missing required Tag
                    throw "Missing Required Tag: " + tag_req[i];
                }
            }
            //At least 1 plan?
            if (plans.length < 1) {
                throw "Need at least 1 plan.";
            }
            //Check if all required fields are present in plans
            var plan_req = ["target", "ra_h", "ra_m", "ra_s", "dec_sign", "dec_d", "dec_m", "dec_s", "priority"];
            for (i = 0; i < plans.length; i++) {
                var p = plans[i];
                for (j = 0; j < plan_req.length; j++) {
                    if (!(plan_req[j] in p)) {
                        throw "Plan #" + (i+1) + " missing required field: " + plan_req[j];
                    }
                }
            }

            var DB = Scheduler.Database;

            //Create outer RTML object and fill in with Contact details.
            var RTML = new ActiveXObject("XML_RTML23.RTML");
            RTML.Version = 2.3;                                                     // Required!
            RTML.Contact = new ActiveXObject("XML_RTML23.Contact");
            RTML.Contact.User = tags.CONTACT;
            if (User.Username != "localweb") {
                RTML.Contact.User += " [ACP " + User.Username + "]";                // Insert special tag for real web
                if (User.WantsCompress) RTML.Contact.User += '#';                   // And User's compression flag if enabled
            }
            RTML.Contact.Email = tags.CONTACT_EMAIL;
            RTML.Contact.Organization = tags.CONTACT_ORG;

            //Build a Request for each plan.
            for (i = 0; i < plans.length; i++) {
                var p = plans[i];
                var REQ = new ActiveXObject("XML_RTML23.Request");
                RTML.Requests.Add(REQ);                                        // Creates a Plan in ACPS
                REQ.ID = p.target;                                             // Plan name = object name
                REQ.UserName = tags.CONTACT;
                REQ.Project = tags.PROJECT;
                if ("monitor" in p) {
                    var m = parseInt(p.monitor);
                    if (m > 0) {
                        //Response.Write("<p>Monitor: " + m + "</p>");
                        REQ.Reason = "Monitor=" + m; //ACP Hack for adding a Monitor attribute
                    }
                }

                //Observation & Constraints: 1 per Project for Photometry
                var SCH = new ActiveXObject("XML_RTML23.Schedule");
                REQ.Schedule = SCH;
                SCH.Priority = Number(p.priority);
                var hz = Number(p.horizon); //Horizon Constraint
                if (hz > 0) {
                    SCH.Horizon = hz;
                } else {
                    SCH.Horizon = 35;
                }
                var am = Number(p.airmass); //Airmass Maximum Constraint
                if (am > 1) {
                    SCH.AirmassRange = new ActiveXObject("XML_RTML23.AirmassRange");
                    SCH.AirmassRange.Minimum = 1.0; //Airmass Minimum is always 1.0
                    SCH.AirmassRange.Maximum = am;
                }
                //Response.Write("<p>SCH Done</p>");

                //Sky Conditions
                //var conditions = new Array("POOR", "FAIR", "GOOD", "EXCELLENT");
                var conditions = { 'POOR': 1, 'FAIR': 2, 'GOOD': 3, 'EXCELLENT': 4 };
                if (p.sky_condition.toUpperCase() in conditions) {
                    SCH.SkyCondition = conditions[p.sky_condition.toUpperCase()];
                } else {
                    SCH.SkyCondition = 2;
                    Response.Write("<p>No Valid Sky Condition specified. Default to Fair</p>");
                }

                //Date limits
                var date_first = null;
                var date_last = null;
                if (p.date_first !== "") {
                    date_first = new Date(p.date_first);
                    date_first.setHours(16); //Middle of the day Eastern
                }
                if (p.date_last !== "") {
                    date_last = new Date(p.date_last);
                    date_last.setHours(16); //Middle of the day Eastern
                    //Set latest to the day after to allow imaging all night on the specified evening.
                    date_last.setUTCDate(date_last.getUTCDate() + 1);
                }
                if (date_first !== null || date_last !== null) {
                    var TR = new ActiveXObject("XML_RTML23.TimeRange");
                    SCH.TimeRange = TR;
                    if (date_first !== null) {
                        TR.Earliest = date_first.getVarDate();
                    } else {
                        //Use current time in UTC, but import it without timezone. ACP hack copied from asphotosingle.asp
                        TR.Earliest = new Date(Date.parse(new Date().toUTCString().replace(/UTC/, ""))).getVarDate();
                    }
                    if (date_last !== null) {
                        TR.Latest = date_last.getVarDate();
                    } else {
                        //Use a far future date
                        TR.Latest = new Date(2050, 11, 31, 23, 59, 59).getVarDate();
                    }
                }

                //Target for Observation: 1 per Observation for Photometry
                var ra = Number(p.ra_h) + Number(p.ra_m) / 60.0 + Number(p.ra_s) / 3600.0; //RA hh:mm:ss.s
                var dec = Number(p.dec_d) + Number(p.dec_m) / 60.0 + Number(p.dec_s) / 3600.0; //DEC hh:mm:ss.s
                if (p.dec_sign.toUpperCase().slice(0,3) === "NEG") {
                    dec = -dec;
                }
                var TGT = new ActiveXObject("XML_RTML23.Target");
                REQ.Targets.Add(TGT);
                TGT.Name = p.target;
                TGT.Coordinates = new ActiveXObject("XML_RTML23.Coordinates");
                TGT.Coordinates.RightAscension = 15 * ra; //Convert to degrees
                TGT.Coordinates.Declination = dec;
                TGT.Description = "";
                //Response.Write("<p>TGT Done</p>");

                //Find exposure headers and iterate through them
                for (hk in p) {
                    //Response.Write("<p>Checking: " + hk + "</p>")
                    if (hk.slice(-9) === "_exposure") {
                        //Found an exposure
                        var filt = hk.slice(0, -9);
                        //Response.Write("<p>filt: " + filt + "</p>")
                        var exp_time = Number(p[filt + '_exposure']);
                        //Response.Write("<p>exp_time: " + exp_time + "</p>")
                        var exp_count = Number(p[filt + '_count']);
                        //Response.Write("<p>exp_count: " + exp_count + "</p>")
                        if (exp_time > 0 && exp_count > 0) {
                            //Response.Write("<p>OK!</p>")
                            filt = filter_selection(filt); //Convert to ACP True Filter Name
                            //Response.Write("<p>ACP filt: " + filt + "</p>")
                            var PIC = new ActiveXObject("XML_RTML23.Picture");
                            TGT.Pictures.Add(PIC);
                            PIC.Filter = filt;
                            PIC.ExposureTime = exp_time;
                            PIC.Name = filt;
                            PIC.Description = "#nopreview";
                            PIC.Binning = 2;
                            PIC.count = exp_count;
                            Response.Write("<p>Adding Filter: " + filt + " to " + p.target + " : " + exp_count + " x " + exp_time + "</p>");
                        } else {
                            //Ignoring filter
                            //Response.Write("<p>Ignore Filter: " + filt + "</p>");
                        }

                    }
                }
            }
            Response.Write("<p>Returning RTML: "+typeof RTML+"</p>")
            return RTML;
        }
    </script>
    <script src="/ac/iframecss.js" runat="client"></script>
    <!-- parent's stylesheets get inserted here -->
    <style>
        /* Now remove borders, margins, and padding 
         * from parent's tiddler and viewer  classes
         */
        .tiddler { border: none; margin: 0; padding: 0;}
        .viewer { border: none; margin: 0; padding: 0;}
    </style>
</head>
<body>
<div class="tiddler" id="tdiv"><div class="viewer" id="vdiv">
<% 
    if(!User.CanUpload && !User.IsAdministrator) {
        Response.Write("<p>No permission to upload</p>");
    } else {
        if(Request.ServerVariables("request_method").toLowerCase() != "post") 
        {
%>
<form style="margin-bottom: 4px;margin-top:2px;" name="upcsv_form" id="upcsv_form"
                    method="POST" 
                    enctype="multipart/form-data" 
                    action="<%= Request.ServerVariables("script_name") %>">
<h2>1. Select Local CSV File</h2>
<input type="file" class="upload" name="File1" id="upcsv_File1" size="50"><br>
<h2>2. Submit CSV Request to Scheduler</h2>
<a class="button" style="margin-left:0px;" 
        title="Enter the requests into the Schedule database"
        href="javascript: document.upcsv_form.submit()">Submit RTML</a>&nbsp;&nbsp;&nbsp;
<input type="checkbox" name="autoSubmit">Enable immediately</input>
</form>
<% 
        } else {
            //
            // POST: Import the RTML. The If nesting is because the stuff at the
            // endhas to run to make the iframe work inside the TiddlyWiki.
            //
            //if(Request.Form("FileName")) 
            if (true)
            {                         // No file uploaded...
                var DB = Scheduler.Database;
                var RTI;
                var tmpSt = null;
                try {
                    // 1. Get the CSV into a buffer for modification
                    var FSO = new ActiveXObject("Scripting.FileSystemObject");
                    var csvFile = FSO.OpenTextFile(Request.Form("FilePath"));
                    var csvBuf = csvFile.ReadAll();
                    csvFile.Close();

                    // 2. Delete the tempfile provided by the webserver
                    //  //FSO.DeleteFile(Request.Form("FilePath"));

                    var ret = parse_atmob_csv(csvBuf);
                    var tags = ret[0];
                    var plans = ret[1];
                    Response.Write("<p>Proposal=" + tags['PROPOSAL'] + "</p>")
                    for (i = 0; i < plans.length; i++) {
                        Response.Write("<p>Target[" + i + "]=" + plans[i].target + "</p>")
                    }
                    var RTML = generate_photometry_rtml(tags, plans);
                    Response.Write("<p>RTML: " + RTML + "</p>")

                    //Peforms the RTML write and import
                    var tmpFn = Server.MapPath("/plans/" + User.Username) +
                        "\\last-rtml-from-web.txt";
                    Response.Write("<p>Writing to: " + tmpFn + "</p>");
                    tmpSt = FSO.CreateTextFile(tmpFn, true);
                    tmpSt.Write(RTML.XML("", true));
                    tmpSt.Close();
                    tmpSt = null;                                                       // [sentinel] for finally
                    Response.Write("<p>File written</p>");
                    RTI = new ActiveXObject("DC3.RTML23.Importer");
                    RTI.DB = DB;
                    RTI.Import(tmpFn);
                    var R = RTI.Projects.Item(0);
                    R.Description = tags.DESCRIPTION;
                    R.Update();

                    var submit = ((Request.Form("autoSubmit") == undefined) ? false : true);
                    if (submit) {
                        R.Disabled = false;
                        R.Update;
                        var eP = new Enumerator(RTI.Plans); // Plans created by this RTML
                        for (; !eP.atEnd(); eP.moveNext()) {
                            var P = eP.item();
                            P.Resubmit();
                        }
                        Response.Write("</p>\r\n<p><b>The newly added Plans are already eligible to run.</b></p>\r\n");
                    } else {
                        Response.Write("</p>\r\n<p><b>Enable the Plans with the <a href=\"/sc/index.asp\" target=\"_blank\">" +
                            "Schedule Browser</a> when you want it to become eligible to run.</b></p>\r\n");
                    }
                    Response.Write("<a href='" + Request.ServerVariables("script_name") + "' target='_self'>Upload another.</a>");
                }      
                catch(ex) 
                {
                    Response.Write("<p>CSV failed: " + (ex.message ? ex.message : ex) + "</p>");
                    Response.Write("<a href='" + Request.ServerVariables("script_name") + "' target='_self'>Upload another.</a>");
                }
                finally
                {
                    if (tmpSt !== null) tmpSt.Close();
                    DB.CurrentUser = 0;
                    RTML = null;
                    RTI = null;
                }
            }
            else
            {
                Response.Write("<br>No CSV file. <a href='" + Request.ServerVariables("script_name") + 
                                    "' target='_self'>Try again.</a>");
            }
        }
    }
%>
</div></div>
<script language="Javascript" type="text/javascript" runat="client">
    var tdiv = document.getElementById("tdiv");
    document.body.style.backgroundColor = getStyle(tdiv, 'background-color');
    parent.document.getElementById("asuploadaicsv").height = tdiv.offsetHeight + 12;
</script>
</body></html>
